local_backend: true
backend:
  name: git-gateway
  branch: main
# publish_mode: editorial_workflow
media_folder: 'src/uploads'
public_folder: '/uploads'

theme: &THEME
  label: 'Theme'
  name: 'theme'
  widget: 'select'
  options: ['light', 'nile']
  required: false

blocks: &BLOCKS
  label: 'Blocks'
  name: 'blocks'
  widget: 'list'
  types:
    - label: 'Hero'
      name: 'hero'
      widget: object
      fields:
        - { label: 'Title', name: 'title', widget: 'string' }
        - { label: 'Eyebrow', name: 'eyebrow', widget: 'string' }
        - { label: 'Content', name: 'content', widget: 'markdown' }
        - label: 'Buttons'
          name: 'buttons'
          widget: 'list'
          collapsed: true
          required: false
          fields:
            - { label: 'Text', name: 'text', widget: 'string' }
            - { label: 'Link', name: 'link', widget: 'string' }
        - { label: 'Image', name: 'image', widget: 'image' }
    - label: 'Intro'
      name: 'intro'
      widget: 'object'
      fields:
        - { label: 'Image', name: 'image', widget: 'image' }
        - { label: 'Alt', name: 'alt', widget: 'string' }
        - { label: 'Eyebrow', name: 'eyebrow', widget: 'string' }
        - { label: 'Title', name: 'title', widget: 'string' }
        - { label: 'Content', name: 'content', widget: 'markdown' }
        - label: 'Button'
          name: 'button'
          widget: 'object'
          required: false
          fields:
            - { label: 'Text', name: 'text', widget: 'string', required: false }
            - { label: 'Link', name: 'link', widget: 'string', required: false }
    - label: 'Services'
      name: 'services'
      widget: 'object'
      fields:
        - { label: 'Eyebrow', name: 'eyebrow', widget: 'string' }
        - { label: 'Title', name: 'title', widget: 'string' }
        - { label: 'Content', name: 'content', widget: 'markdown' }
        - label: 'Button'
          name: 'button'
          widget: 'object'
          required: false
          fields:
            - { label: 'Text', name: 'text', widget: 'string', required: false }
            - { label: 'Link', name: 'link', widget: 'string', required: false }
        - label: 'Specialisms'
          name: 'specialisms'
          widget: list
          collapsed: true
          required: false
          fields:
            - { label: 'Service Name', name: 'servicename', widget: 'string' }
            - { label: 'Icon', name: 'icon', widget: 'image' }
            - { label: 'Text', name: 'text', widget: 'markdown' }
            - { label: 'Link', name: 'link', widget: 'string', default: '/specialization', required: false }
    - label: 'Work'
      name: 'work'
      widget: 'object'
      fields:
        - { label: 'Eyebrow', name: 'eyebrow', widget: 'string' }
        - { label: 'Title', name: 'title', widget: 'string' }
        - { label: 'Count', name: 'count', widget: 'string' }
        - { label: 'Show Button', name: 'showbutton', widget: 'boolean' }
    - label: 'Specialization'
      name: 'specialization'
      widget: 'object'
      fields:
        - { label: 'Eyebrow', name: 'eyebrow', widget: 'string' }
        - { label: 'Content', name: 'content', widget: 'markdown' }
        - label: 'Tools'
          name: 'tools'
          widget: list
          collapsed: true
          required: false
          fields:
            - { label: 'Program Name', name: 'toolname', widget: 'string' }
        - label: 'Skills'
          name: 'skills'
          widget: list
          collapsed: true
          required: false
          fields:
            - { label: 'Skill Name', name: 'skillname', widget: 'string' }
        - label: 'Button'
          name: 'button'
          widget: 'object'
          required: false
          fields:
            - { label: 'Text', name: 'text', widget: 'string', required: false }
            - { label: 'Link', name: 'link', widget: 'string', required: false }
    - label: 'Offerings'
      name: 'offerings'
      widget: 'object'
      fields:
        - { label: 'Eyebrow', name: 'eyebrow', widget: 'string' }
        - { label: 'Title', name: 'title', widget: 'string' }
        - label: 'Button'
          name: 'button'
          widget: 'object'
          required: false
          fields:
            - { label: 'Text', name: 'text', widget: 'string', required: false }
            - { label: 'Link', name: 'link', widget: 'string', required: false }
        - label: 'Services'
          name: 'services'
          widget: list
          collapsed: true
          required: false
          fields:
            - { label: 'Service Name', name: 'servicename', widget: 'string' }
            - { label: 'Icon', name: 'icon', widget: 'image' }
            - { label: 'Content', name: 'content', widget: 'markdown' }
    - label: 'Contact'
      name: 'contact'
      widget: 'object'
      fields:
        - { label: 'Title', name: 'title', widget: 'text' }
    - label: 'Text'
      name: 'text'
      widget: 'object'
      fields:
        - { label: 'Content', name: 'content', widget: 'markdown' }
    - label: 'Alert'
      name: 'alert'
      widget: 'object'
      fields:
        - { label: 'Title', name: 'title', widget: 'string' }
        - { label: 'Content', name: 'content', widget: 'markdown' }

meta: &META
  label: 'Meta'
  name: 'meta'
  widget: 'object'
  collapsed: true
  required: false
  fields:
    - { label: 'Title', name: 'title', widget: 'string', required: false }
    - { label: 'Description', name: 'desc', widget: 'string', required: false }
    - { label: 'Author', name: 'author', widget: 'string', required: false }

social: &SOCIAL
  label: 'Social'
  name: 'social'
  widget: 'object'
  collapsed: true
  required: false
  fields:
    - { label: 'Image', name: 'image', widget: 'image', required: false }

navigation: &NAVIGATION
  label: 'Navigation'
  name: 'eleventyNavigation'
  widget: 'object'
  collapsed: true
  required: false
  fields:
    - { label: 'Key', name: 'key', widget: 'string', required: false }
    - { label: 'Parent', name: 'parent', widget: 'string', required: false }
    - { label: 'Icon', name: 'icon', widget: 'image', required: false }
    - { label: 'Image', name: 'image', widget: 'image', required: false }
    - { label: 'Excerpt', name: 'excerpt', widget: 'string', required: false }
    - { label: 'Order', name: 'order', widget: 'number', required: false }

collections:
  - label: 'Pages'
    name: 'pages'
    folder: 'src'
    identifier_field: 'title'
    create: true
    extension: 'md'
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
    nested:
      depth: 4
      summary: '{{title}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'layouts/page.njk' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - *BLOCKS
      - *META
      - *SOCIAL
      - *NAVIGATION
  - label: 'Projects'
    name: 'projects'
    folder: 'src/work/items'
    identifier_field: 'title'
    create: true
    extension: 'md'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: "Tagline", name: "tagline", widget: "string" }
      - { label: 'Thumbnail', name: 'thumbnail', widget: 'image' }
      - label: "Services"
        name: "services"
        widget: "select"
        multiple: true
        options: ["Design", "Development", "Branding"]
        default: ["Design"]
      - label: 'Blocks'
        name: 'projects'
        widget: 'list'
        types:
          - label: 'Hero'
            name: 'hero'
            widget: object
            fields:
              - { label: 'Tagline', name: 'tagline', widget: 'string' }
              - { label: 'Image', name: 'image', widget: 'image' }
              - { label: 'Image Alt', name: 'alt', widget: 'string' }
          - label: 'Intro'
            name: 'intro'
            widget: object
            fields:
              - { label: 'Content', name: 'content', widget: 'markdown' }
              - { label: 'Client', name: 'client', widget: 'string' }
              - { label: 'Client Link', name: 'clientlink', widget: 'string', required: false }
              - { label: 'Year', name: 'year', widget: 'string' }
              - label: 'Button'
                name: 'button'
                widget: 'object'
                required: false
                fields:
                  - { label: 'Text', name: 'text', widget: 'string', required: false }
                  - { label: 'Link', name: 'link', widget: 'string', required: false }
          - label: 'Image Full'
            name: 'imagefull'
            widget: 'object'
            fields:
              - { label: 'Image', name: 'image', widget: 'image' }
              - { label: 'Alt', name: 'alt', widget: 'string' }
              - { label: 'Background Hue', name: 'background', widget: 'string' }
          - label: 'Image Double'
            name: 'imagedouble'
            widget: 'object'
            fields:
              - { label: 'Image', name: 'imageone', widget: 'image' }
              - { label: 'Alt', name: 'altone', widget: 'string' }
              - { label: 'Image', name: 'imagetwo', widget: 'image' }
              - { label: 'Alt', name: 'alttwo', widget: 'string' }
              - { label: 'Background Hue', name: 'background', widget: 'string' }
          - label: 'Text'
            name: 'text'
            widget: 'object'
            fields:
              - { label: 'Eyebrow', name: 'eyebrow', widget: 'string' }
              - { label: 'Content', name: 'content', widget: 'markdown' }
      - *META